name: Love.js CI

env:
  BUILD_DIR: build
  EMSDK_VERSION: 2.0.2
  EMSDK_CACHE_DIR: emsdk-cache

on:
  push:
    branches: [master, ci*]
    tags: [pre*, v*]
  pull_request:
    branches: [master]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout love.js
        uses: actions/checkout@v4

      - name: Checkout megasource
        uses: actions/checkout@v4
        with:
          repository: 26F-Studio/megasource
          ref: emscripten
          path: megasource

      - name: Checkout love
        uses: actions/checkout@v4
        with:
          repository: 26F-Studio/love-wasm
          ref: 32e0716b43a51686f5fa9ac04ca08b6410b698a5
          path: megasource/libs/love
          submodules: recursive

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: ${{ env.EMSDK_CACHE_DIR }}

      - name: Build release version
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          emcmake cmake -B ${{ env.BUILD_DIR }} -S megasource -DCMAKE_BUILD_TYPE=Release -DLOVE_JIT=0
          emmake make -C ${{ env.BUILD_DIR }} -j
      - name: Copy files
        run: |
          ls ${{ env.BUILD_DIR }}/love
          cp ${{ env.BUILD_DIR }}/love/love.js src/compat/
          cp ${{ env.BUILD_DIR }}/love/love.wasm src/compat/
          cp ${{ env.BUILD_DIR }}/love/love.worker.js src/release/

      - name: Pack all files
        run: |
          7z a -tzip -x!.github -x!${{ env.BUILD_DIR }} -x!${{ env.EMSDK_CACHE_DIR }} -x!megasource love.js.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Love.js_Release
          path: love.js.zip

  build-compatible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout love.js
        uses: actions/checkout@v4

      - name: Checkout megasource
        uses: actions/checkout@v4
        with:
          repository: Davidobot/megasource
          ref: emscripten
          path: megasource

      - name: Checkout love
        uses: actions/checkout@v4
        with:
          repository: Davidobot/love
          ref: emscripten
          path: megasource/libs/love

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: ${{ env.EMSDK_CACHE_DIR }}

      - name: Build compat version
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          emcmake cmake -B ${{ env.BUILD_DIR }} -S megasource -DCMAKE_BUILD_TYPE=Release -DLOVE_JIT=0 -DLOVEJS_COMPAT=1 -DSEXPORT_ALL=1 -DSMAIN_MODULE=1 -DSERROR_ON_UNDEFINED_SYMBOLS=0
          emmake make -C ${{ env.BUILD_DIR }} -j
      - name: Copy files
        run: |
          ls ${{ env.BUILD_DIR }}/love
          cp ${{ env.BUILD_DIR }}/love/love.js src/compat/
          cp ${{ env.BUILD_DIR }}/love/love.wasm src/compat/

      - name: Pack all files
        run: |
          7z a -tzip -x!.github -x!${{ env.BUILD_DIR }} -x!${{ env.EMSDK_CACHE_DIR }} -x!megasource love.js.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Love.js_Compatible
          path: love.js.zip
