name: Love.js CI

env:
  BUILD_DIR: "build"
  EMSDK_VERSION: "latest"
  EMSDK_CACHE_DIR: "emsdk-cache"

on:
  push:
    branches: [master, ci*]
    tags: [pre*, v*]
  pull_request:
    branches: [master]

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout love.js
        uses: actions/checkout@v4

      - name: Checkout megasource
        uses: actions/checkout@v4
        with:
          repository: Davidobot/megasource
          ref: emscripten
          path: megasource

      - name: Checkout love
        uses: actions/checkout@v4
        with:
          repository: Davidobot/love
          ref: emscripten
          path: love

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: ${{ env.EMSDK_CACHE_DIR }}

      - name: Build release version
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          emcmake cmake -B ${{ env.BUILD_DIR }} -S megasource -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLOVE_JIT=0
          emmake make -C ${{ env.BUILD_DIR }} -j
      - name: Copy files
        run: |
          ls
          ls ${{ env.BUILD_DIR }}
          ls love
          cp love/love.js src/compat/
          cp love/love.wasm src/compat/
          cp love/love.worker.js src/release/

      - name: Pack all files
        run: |
          7z a -tzip -x!.github -x!${{ env.BUILD_DIR }} -x!${{ env.EMSDK_CACHE_DIR }} -x!love -x!megasource love.js.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Love.js_Release
          path: love.js.zip

  build-compatible:
    runs-on: windows-latest
    steps:
      - name: Checkout love.js
        uses: actions/checkout@v4

      - name: Checkout megasource
        uses: actions/checkout@v4
        with:
          repository: Davidobot/megasource
          ref: emscripten
          path: megasource

      - name: Checkout love
        uses: actions/checkout@v4
        with:
          repository: Davidobot/love
          ref: emscripten
          path: love

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: ${{ env.EMSDK_CACHE_DIR }}

      - name: Build compat version
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          emcmake cmake -B ${{ env.BUILD_DIR }} -S megasource -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLOVE_JIT=0 -DLOVE_COMPAT=1 -DLOVEJS_COMPAT=1
          emmake make -C ${{ env.BUILD_DIR }} -j
      - name: Copy files
        run: |
          ls
          ls ${{ env.BUILD_DIR }}
          ls love
          cp love/love.js src/compat/
          cp love/love.wasm src/compat/

      - name: Pack all files
        run: |
          7z a -tzip -x!.github -x!${{ env.BUILD_DIR }} -x!${{ env.EMSDK_CACHE_DIR }} -x!love -x!megasource love.js.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Love.js_Compatible
          path: love.js.zip
